#!/bin/sh

# Keyboard layouts and numlock
numlockx on
setxkbmap -layout fr,ar -option 'grp:alt_shift_toggle'

# Load Xresources
xrdb -load $XDG_CONFIG_HOME/X11/Xresources

# Run xrandr screen layout script
sh $XDG_CONFIG_HOME/screenlayout/default.sh

# Run compositor in background
picom -b

# Add background
feh --no-fehbg --bg-scale $XDG_CONFIG_HOME/wallpaper/map_of_maths.png

# Start MusicPlayerDaemon
mpd &

# Start i3 windows manager
exec i3
